List<String> winCommands = [
  "Ace",
  "Admirable",
  "Awesome",
  "Awesomesauce",
  "Beautiful",
  "Bonzer",
  "Bosting",
  "Brilliant",
  "Capital",
  "Champion",
  "Class",
  "Cool",
  "Eminent",
  "Excellent",
  "Exceptional",
  "Extremely Good",
  "Fabulous",
  "Fantastic",
  "Fine",
  "First-Class",
  "First-Rate",
  "Great",
  "Legit",
  "Magic",
  "Magnificent",
  "Marvelous",
  "Matchless",
  "Mind-Blowing",
  "On Fleek",
  "Out Of This World",
  "Outstanding",
  "Outstanding",
  "Peerless",
  "Perfect",
  "Preeminent",
  "Ripping",
  "Smashing",
  "Spiffing",
  "Splendid",
  "Sterling",
  "Sublime",
  "Super",
  "Superb",
  "Superior",
  "Superlative",
  "Supreme",
  "Terrific",
  "Tip-Top",
  "Top-Notch",
  "Topping",
  "Tremendous",
  "Very Good",
  "Wizard",
  "Wonderful",
  "Worthy",
];
